### ISSUE TITLE
[PeanutButter.INI] - Not possible to persist ini file if there is a SectionSeparator and no section

### ISSUE THREAD

**Issue by Prochy** [fluffynuts/PeanutButter#98]
In case, I have ini file and I remove a last section from that file and try to save via Persist(), it fails on trying to remove non existing item.

## Expected Behavior
Persist doesn't throw an exception and the file is empty after the call.

## Actual Behavior
An exception "Exception is "Index was out of range. Must be non-negative and less than the size of the collection." is thrown.

## Steps to Reproduce the Problem

  1. Load ini file that contains one section
  2. Remove the section
  3. Call Persist()

## Specifications

  - Platform: Windows
  - PeanutButter Component: INI
  - PeanutButter Version: 3.0.160
  - 
## Stack

```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at PeanutButter.INI.INIFile.GetLinesForCurrentData(PersistStrategies persistStrategy) in C:\source\PeanutButter\source\INI\PeanutButter.INI\INIFile.cs:line 1092
   at PeanutButter.INI.INIFile.Persist(String saveToPath, PersistStrategies persistStrategy, Encoding encoding) in C:\source\PeanutButter\source\INI\PeanutButter.INI\INIFile.cs:line 980
   at PeanutButter.INI.INIFile.Persist(Encoding encoding) in C:\source\PeanutButter\source\INI\PeanutButter.INI\INIFile.cs:line 919
   at PeanutButter.INI.INIFile.Persist() in C:\source\PeanutButter\source\INI\PeanutButter.INI\INIFile.cs:line 913
   at PeanutButter.INI.Tests.TestINIFile.Construction.MergingConfigurations.Persistence.PersistEmptyIniWithLineSeparator() in C:\source\PeanutButter\source\INI\PeanutButter.INI.Tests\TestINIFile.cs:line 347
```

**Comment by fluffynuts** [comment]
@Prochy please test with version 3.0.163 & re-open if you're still having trouble.

**Comment by Prochy** [comment]
@fluffynuts thanks for quick fix, it is fine now.
